// <auto-generated />
namespace HomeWork_06.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addColumnage : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addColumnage));
        
        string IMigrationMetadata.Id
        {
            get { return "202403291359008_addColumn-age"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
